import logo from "@/assets/logo.png";

export const APPS_LIST = [
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "https://youtube.com",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
  {
    label: "Solicitações",
    icon: logo,
    tag: "solicitacoes",
    url: "/inicio",
  },
];
